import './globals.css'
import { Nunito } from 'next/font/google'

import ClientOnly from './components/ClientOnly'
import NavBar from './components/navbar/NavBar'
import Modal from './components/modals/Modal'

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${font.className}`}>
        <ClientOnly>
          <Modal isOpen/>
          <NavBar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
